name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'web-fake-book-server'
          heroku_email: 'sean.m.mcquaid@gmail.com'
        env:
          HD_NODE_ENV: production
          HD_PORT: 8080
          HD_HOST: localhost
          HD_JET_LOGGER_MODE: FILE
          HD_JET_LOGGER_FILEPATH: jet-logger.log
          HD_JET_LOGGER_TIMESTAMP: TRUE
          HD_JET_LOGGER_FORMAT: LINE
          HD_MONGO_URL: ${{ secrets.MONGO_URL }}
