name: Pull Request
on:
  pull_request:
    branches: [main]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: testing
      PORT: 8080
      HOST: localhost
      JET_LOGGER_MODE: FILE
      JET_LOGGER_FILEPATH: jet-logger.log
      JET_LOGGER_TIMESTAMP: TRUE
      JET_LOGGER_FORMAT: LINE
      MONGO_URL: ${{ secrets.MONGO_URL }}
    steps:
      - name: Setup GHA
        uses: actions/checkout@v2
      - name: Install modules
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Run Unit Tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
